version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - /Users/gopikum/pegasus-poc/ClusterBuild/SharedVolumes/cobrix-poc:/cobrix-poc
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8083:8083"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8083"
    volumes:
      - /Users/gopikum/pegasus-poc/ClusterBuild/SharedVolumes/cobrix-poc:/cobrix-poc
  spark-worker-2:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8082"
    volumes:
      - /Users/gopikum/pegasus-poc/ClusterBuild/SharedVolumes/cobrix-poc:/cobrix-poc      
