(
      SELECT
      SC.STATEMENT_CYCLE_UID,
      SC.ACCOUNT_UID,
      SC.START_DT,
      SC.STATEMENT_CYCLE_NO
      FROM
      CARDINAL.STATEMENT_CYCLE SC
      JOIN
      (SELECT
      SC2.ACCOUNT_UID,
      SC2.START_DT,
      ROW_NUMBER() OVER(PARTITION BY SC2.ACCOUNT_UID
      ORDER BY SC2.START_DT DESC) RN
      FROM
      CARDINAL.STATEMENT_CYCLE SC2) CURR_SC
      ON  CURR_SC.ACCOUNT_UID=SC.ACCOUNT_UID
      AND CURR_SC.START_DT=SC.START_DT
      AND CURR_SC.RN=1
      WHERE
      TRUNC(SC.END_DT) is NULL)
